# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(597, 481)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditSigma600 = QtWidgets.QLineEdit(Dialog)
        self.lineEditSigma600.setGeometry(QtCore.QRect(480, 30, 91, 20))
        self.lineEditSigma600.setObjectName("lineEditSigma600")
        self.lineEditSigma300 = QtWidgets.QLineEdit(Dialog)
        self.lineEditSigma300.setGeometry(QtCore.QRect(480, 60, 91, 20))
        self.lineEditSigma300.setObjectName("lineEditSigma300")
        self.lineEditSigma200 = QtWidgets.QLineEdit(Dialog)
        self.lineEditSigma200.setGeometry(QtCore.QRect(480, 90, 91, 20))
        self.lineEditSigma200.setObjectName("lineEditSigma200")
        self.lineEditSigma100 = QtWidgets.QLineEdit(Dialog)
        self.lineEditSigma100.setGeometry(QtCore.QRect(480, 120, 91, 20))
        self.lineEditSigma100.setObjectName("lineEditSigma100")
        self.lineEditSigma6 = QtWidgets.QLineEdit(Dialog)
        self.lineEditSigma6.setGeometry(QtCore.QRect(480, 150, 91, 20))
        self.lineEditSigma6.setObjectName("lineEditSigma6")
        self.lineEditSigma3 = QtWidgets.QLineEdit(Dialog)
        self.lineEditSigma3.setGeometry(QtCore.QRect(480, 180, 91, 20))
        self.lineEditSigma3.setObjectName("lineEditSigma3")
        self.label600 = QtWidgets.QLabel(Dialog)
        self.label600.setGeometry(QtCore.QRect(420, 30, 51, 20))
        self.label600.setObjectName("label600")
        self.label300 = QtWidgets.QLabel(Dialog)
        self.label300.setGeometry(QtCore.QRect(420, 60, 51, 20))
        self.label300.setObjectName("label300")
        self.label200 = QtWidgets.QLabel(Dialog)
        self.label200.setGeometry(QtCore.QRect(420, 90, 51, 20))
        self.label200.setObjectName("label200")
        self.label100 = QtWidgets.QLabel(Dialog)
        self.label100.setGeometry(QtCore.QRect(420, 120, 51, 20))
        self.label100.setObjectName("label100")
        self.label6 = QtWidgets.QLabel(Dialog)
        self.label6.setGeometry(QtCore.QRect(420, 150, 51, 20))
        self.label6.setObjectName("label6")
        self.label3 = QtWidgets.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(420, 180, 51, 20))
        self.label3.setObjectName("label3")
        self.label3_2 = QtWidgets.QLabel(Dialog)
        self.label3_2.setGeometry(QtCore.QRect(390, 210, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label3_2.setFont(font)
        self.label3_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_2.setObjectName("label3_2")
        self.labelTy = QtWidgets.QLabel(Dialog)
        self.labelTy.setGeometry(QtCore.QRect(420, 240, 51, 20))
        self.labelTy.setObjectName("labelTy")
        self.labelK = QtWidgets.QLabel(Dialog)
        self.labelK.setGeometry(QtCore.QRect(420, 270, 55, 20))
        self.labelK.setObjectName("labelK")
        self.labelm = QtWidgets.QLabel(Dialog)
        self.labelm.setGeometry(QtCore.QRect(420, 300, 51, 20))
        self.labelm.setObjectName("labelm")
        self.labelR2 = QtWidgets.QLabel(Dialog)
        self.labelR2.setGeometry(QtCore.QRect(420, 330, 51, 20))
        self.labelR2.setObjectName("labelR2")
        self.lineEditTy = QtWidgets.QLineEdit(Dialog)
        self.lineEditTy.setGeometry(QtCore.QRect(480, 240, 91, 20))
        self.lineEditTy.setObjectName("lineEditTy")
        self.lineEditK = QtWidgets.QLineEdit(Dialog)
        self.lineEditK.setGeometry(QtCore.QRect(480, 270, 91, 20))
        self.lineEditK.setObjectName("lineEditK")
        self.lineEditm = QtWidgets.QLineEdit(Dialog)
        self.lineEditm.setGeometry(QtCore.QRect(480, 300, 91, 20))
        self.lineEditm.setObjectName("lineEditm")
        self.lineEditR2 = QtWidgets.QLineEdit(Dialog)
        self.lineEditR2.setGeometry(QtCore.QRect(480, 330, 91, 20))
        self.lineEditR2.setObjectName("lineEditR2")
        self.pushButtonCalculate = QtWidgets.QPushButton(Dialog)
        self.pushButtonCalculate.setEnabled(False)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(400, 360, 181, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCalculate.setFont(font)
        self.pushButtonCalculate.setCheckable(False)
        self.pushButtonCalculate.setChecked(False)
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.pushButtonGraph = QtWidgets.QPushButton(Dialog)
        self.pushButtonGraph.setEnabled(False)
        self.pushButtonGraph.setGeometry(QtCore.QRect(400, 420, 181, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonGraph.setFont(font)
        self.pushButtonGraph.setCheckable(False)
        self.pushButtonGraph.setChecked(False)
        self.pushButtonGraph.setObjectName("pushButtonGraph")
        self.MplWidget = MplWidget(Dialog)
        self.MplWidget.setGeometry(QtCore.QRect(10, 10, 381, 401))
        self.MplWidget.setObjectName("MplWidget")
        self.label3_3 = QtWidgets.QLabel(Dialog)
        self.label3_3.setGeometry(QtCore.QRect(400, 10, 181, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label3_3.setFont(font)
        self.label3_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_3.setObjectName("label3_3")
        self.imagelabel = QtWidgets.QLabel(Dialog)
        self.imagelabel.setGeometry(QtCore.QRect(20, 420, 361, 51))
        self.imagelabel.setText("")
        self.imagelabel.setPixmap(QtGui.QPixmap("codalogo.png"))
        self.imagelabel.setScaledContents(True)
        self.imagelabel.setObjectName("imagelabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Herschel Bulkley Calculator"))
        self.label600.setText(_translate("Dialog", "DR 600"))
        self.label300.setText(_translate("Dialog", "DR 300"))
        self.label200.setText(_translate("Dialog", "DR 200"))
        self.label100.setText(_translate("Dialog", "DR 100"))
        self.label6.setText(_translate("Dialog", "DR 6"))
        self.label3.setText(_translate("Dialog", "DR 3"))
        self.label3_2.setText(_translate("Dialog", "Herschel Bulkley Rheology Model"))
        self.labelTy.setText(_translate("Dialog", "Ty (Pa)"))
        self.labelK.setText(_translate("Dialog", "K (Pa.s^m)"))
        self.labelm.setText(_translate("Dialog", "m"))
        self.labelR2.setText(_translate("Dialog", "R^2"))
        self.pushButtonCalculate.setText(_translate("Dialog", "Calculate"))
        self.pushButtonGraph.setText(_translate("Dialog", "Plot"))
        self.label3_3.setText(_translate("Dialog", "Viscometer Dial Readings"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
